# Définir l'image de base
FROM node:16

# Définir le répertoire de travail
COPY package.json ./
COPY package-lock.json ./
COPY public ./
WORKDIR /src


# Copier les fichiers du projet vers le répertoire de travail
COPY . .

# Installer les dépendances
RUN npm install

# Exposer le port 3000
EXPOSE 3000

# Définir la commande à exécuter lorsque le conteneur est démarré
CMD [ "npm", "run", "start" ]